name: Build and Deploy .NET & Angular

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      working-directory: ./backend/src
      run: dotnet restore
      
    - name: Build and publish
      working-directory: ./backend/src
      run: dotnet publish -c Release -o ./publish
      
    - name: Updating ng dependencies 
      uses: tinesoft/ngx-uptodate@main
      with:
        repo-token: ${{ secrets.TOKEN }}
        project-path: ./frontend/ProEventos-App
        
    - name: Angular Full CI
      uses: colbyhill21/angular-full-ci/@v1.0
      with:
        testcommand: run test:ci
        mocha: true
